#!/usr/bin/env python

Import("env")
Import("env_modules")

env_editortools = env_modules.Clone()

# Godot's own source files
env_editortools.add_source_files(env.modules_sources, "*.cpp")
env_editortools.add_source_files(env.modules_sources, "./property_editors/*.cpp")

env_editortools.Prepend(CPPPATH=["#modules/editortools/property_editors/"])
env_editortools.Prepend(CPPPATH=["."])
